export const availablePropertyTypes = [
  "apartment",
  "house",
  "room",
  "condo",
  "studio",
  "townhouse",
  "villa",
];

export const availableAmenities = [
  "gym",
  "wifi",
  "swimming pool",
  "parking",
  "ac",
  "pet friendly",
  "security system",
  "laundry service",
  "children's play area",
  "bbq area",
  "rooftop terrace",
  "elevator",
  "balcony",
  "library",
  "game room",
  "tennis court",
  "basketball court",
  "sauna",
  "water purifier",
  "grocery delivery",
  "kitchen",
  "furnished",
  "unfurnished",
  "semi-furnished",
  "modular kitchen",
  "wardrobe",
  "geyser",
  "power backup",
  "intercom",
  "maintenance staff",
  "garden",
  "club house",
  "indoor games",
  "outdoor games",
  "cctv",
  "fire safety",
  "rain water harvesting",
  "solar water heating",
  "waste disposal",
  "visitor parking"
];
