export const availablePropertyTypes = [
  "apartment",
  "house",
  "room",
  "condo",
  "studio",
  "townhouse",
  "villa",
];

export const availableAmenities = [
  "gym",
  "wifi",
  "swimming pool",
  "parking",
  "ac",
  "pet friendly",
  "security system",
  "laundry service",
  "children's play area",
  "room service",
  "bbq area",
  "rooftop terrace",
  "elevator",
  "balcony",
  "library",
  "game room",
  "tennis court",
  "basketball court",
  "sauna",
  "hot tub",
  "breakfast included",
  "daily housekeeping",
  "in-room safe",
  "mini-bar",
  "24-hour reception",
  "water purifier",
  "grocery delivery",
  "kitchen",
];
